apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy sau operator
spec:
  project: default
  
  source:
    repoURL: https://github.com/Thahn-Tam/Postresql_Gitops.git
    targetRevision: main
    path: cluster
  
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
