apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy đầu tiên
spec:
  project: default
  
  source:
    repoURL: https://github.com/Thahn-Tam/Postresql_Gitops.git
    targetRevision: main
    path: operator
    helm:
      valueFiles:
        - values.yaml
  
  
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m